
server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 12345
    url: jdbc:postgres://utuydkgnabpbvd:e8400dc332055d1d44a072c2c3942afe8bb9bec1a5226e2443d13b738f0765fb@ec2-34-234-240-121.compute-1.amazonaws.com:5432/dbl1cgep7kdqu7
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000